apiVersion: batch/v1
kind: CronJob
metadata:
  name: postgres-backup
  namespace: scc
spec:
  schedule: "*/10 * * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: postgres-backup
              image: postgres:13-alpine
              env:
                - name: POSTGRES_HOST
                  value: "postgres"
                - name: POSTGRES_DB
                  value: "mydb"
                - name: POSTGRES_USER
                  value: "user"
                - name: POSTGRES_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: postgres-backup-secrets
                      key: postgres-password
              volumeMounts:
                - name: backup-script
                  mountPath: /scripts
                - name: backup-storage
                  mountPath: /backups
              command: ["/bin/sh", "/scripts/backup.sh"]
          volumes:
            - name: backup-script
              configMap:
                name: postgres-backup-script
                defaultMode: 0777
            - name: backup-storage
              persistentVolumeClaim:
                claimName: postgres-backup-pvc
          restartPolicy: OnFailure