name: Build Backend

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      
      - name: Install dependencies
        run: go mod download
      
      - name: Build
        run: go build -o scc-backend

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: scc-backend
          path: scc-backend


  
